#!/usr/bin/env node
"use strict";

var _interopRequire = function (obj) { return obj && obj.__esModule ? obj["default"] : obj; };

var createServer = require("http").createServer;

var ecstatic = _interopRequire(require("ecstatic"));

var join = require("path").join;

var minimist = _interopRequire(require("minimist"));

var argv = minimist(process.argv.slice(2)),
    port = argv.p || 1337,
    dir = process.cwd();

console.log("running server with port: " + argv.p + " and dir: " + argv.dir);

if (argv.dir && typeof argv.dir === "string") {
  if (argv.dir.indexOf("/") === 0) {
    dir = argv.dir;
  } else {
    dir = join(process.cwd(), argv.dir);
  }
}

if (argv.k || argv.kill) {
  process.exit();
}

createServer(ecstatic({
  root: dir,
  showDir: false,
  autoIndex: true,
  defaultExt: "html"
})).listen(port);

console.log("\nScreeninvader dev server listening to port: " + port + "\nand serving static files from " + dir + "\n");
